name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub actions
on: [push, issue_comment, pull_request_target]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version : '20'

      - run: npm install -g bats

      - run: bats -v

  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && startsWith(github.event.comment.body, 'TriagerX') }}
    runs-on: ubuntu-latest
    steps:
      - name: Commenting on the issue
        id: comment
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment succeeded! ✅',
            }); 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}