name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub actions
on: [issue_comment, pull_request_target]
jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && startsWith(github.event.comment.body, 'TriagerX') }}
    runs-on: ubuntu-latest
    steps:
      - name: Commenting on the issue
        id: comment
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment succeeded! ✅',
            }); 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}